name: relational-query-postgresql-pure
version: 0.1.0.0
github: "kakkun61/relational-query-postgresql-pure"
license: BSD3
author: "Kazuki Okamoto (岡本和樹)"
maintainer: "kazuki.okamoto@kakkun61.com"
copyright: "2020 Kazuki Okamoto (岡本和樹), 2013 Kei Hibino"
category: Database

extra-source-files:
  - README.md
  - ChangeLog.md

synopsis: The connector of relational-record and postgresql-pure.
description: You can use postgresql-pure as the backend of relational-record without the HDBC interface.

dependencies:
  - base >= 4 && < 5

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wmissing-exported-signatures
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wno-name-shadowing

library:
  source-dirs: src
  ghc-options:
    - -Wincomplete-uni-patterns
    - -Wmissing-export-lists
    - -Wmissing-import-lists
    - -Wmonomorphism-restriction
  dependencies:
    - HDBC
    - Only
    - containers
    - dlist
    - homotuple >= 0.1.2.0
    - list-tuple >= 0.1.3.0
    - names-th
    - persistable-record
    - postgresql-placeholder-converter
    - postgresql-pure >= 0.2.2.0
    - product-isomorphic
    - relational-query
    - relational-schemas
    - sql-words
    - template-haskell
    - transformers
    - utf8-string

tests:
  db:
    main: Spec.hs
    source-dirs: test-db
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - HDBC-postgresql
      - HDBC-session
      - data-default-class
      - hspec
      - postgresql-pure
      - relational-query
      - relational-query-HDBC
      - relational-query-postgresql-pure
